# Each section from every release note are combined when the
# CHANGELOG.rst is rendered. So the text needs to be worded so that
# it does not depend on any information only available in another
# section. This may mean repeating some details, but each section
# must be readable independently of the other.
#
# Each section note must be formatted as reStructuredText.
---
features:
  - |
    Add a new configuration provider, which schedules new instances of KSM checks to generate metrics
    from ``CustomResourceDefinitions``.

    This new provider works with the ``kube_crd`` listener which listens for ``CustomResourceDefinitions``
    created on the cluster and triggers a new autodiscovery-service for each one.

    This new configuration provider must use the standard kubernetes ``GroupVersionKind`` format in its
    ``AdvancedADIdentifier`` section to apply to a matching ``CustomResourceDefinition``.

    The rest of the configuration is a standard KSM configuration instance.
