---
upgrade:
  - |
    Remote Agent Management now creates a new directory that is at the same level as the current Agent configuration directory.
  
    * Linux: /etc/datadog-agent-exp
    * Windows: C:\ProgramData\Datadog-exp
  
    This directory is used during remote configuration updates and is deleted after the update is complete.
