serverless_cold_start_performance-deb_x64:
  stage: functional_test
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64:$DATADOG_AGENT_BUILDIMAGES
  tags: ["runner:docker"]
  needs: ["linux_x64_go_deps"]
  before_script:
    - !reference [.retrieve_linux_go_deps]
  script:
    - cd cmd/serverless && go build -mod=mod -a -v -tags serverless
    - mkdir -p /tmp/serverless-ci
    - cp serverless /tmp/serverless-ci/datadog-agent
    - cp ../../test/integration/serverless_perf/* /tmp/serverless-ci
    - cd /tmp/serverless-ci # Docker does not like syslinks, that's why it's easier to build the image in /tmp
    - docker build -t datadogci/lambda-extension .
    - ./compute.sh