serverless_cold_start_performance-deb_x64:
  stage: functional_test
  rules:
    - !reference [.except_mergequeue]
    - when: on_success
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/docker_x64$DATADOG_AGENT_BUILDIMAGES_SUFFIX:$DATADOG_AGENT_BUILDIMAGES
  tags: ["runner:docker"]  # Still required as compute.sh is doing a container run
  needs: ["go_deps", "build_serverless-deb_x64"]
  before_script:
    - !reference [.retrieve_linux_go_deps]
    - mkdir -p /tmp/serverless-ci
    - cp cmd/serverless/datadog-agent-x64 /tmp/serverless-ci/datadog-agent
  script:
    - cp test/integration/serverless_perf/* /tmp/serverless-ci
    - cd /tmp/serverless-ci # Docker does not like syslinks, that's why it's easier to build the image in /tmp
    - docker build -t datadogci/lambda-extension .
    - ./compute.sh
