[package]
name = "sharedlibrary-tester"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
core = { version = "0.1.0", path = "../core" }
libloading = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
