apiVersion: v1
kind: Secret
metadata:
  name: datadog-auth-token
type: Opaque
data:
     ccrl
  # use a base64 string: `echo -n '<ThirtyX2XcharactersXlongXtoken>' | base64`
  token: PFRoaXJ0eVgyWGNoYXJhY3RlcnNYbG9uZ1h0b2tlbj4=
