[[constraint]]
  name = "github.com/DataDog/agent-payload"
  version = "4.7.1"

[[constraint]]
  name = "github.com/DataDog/gohai"
  branch = "master"

[[constraint]]
  name = "github.com/DataDog/zstd"
  version = "~v1.3.0"

[[constraint]]
  name = "github.com/DataDog/zstd.v0.5"
  source = "github.com/DataDog/zstd"
  revision = "2b373cbe6ac0c8e6960bbd18026ceb269eef89f5"

[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "~v0.4.7"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/beevik/ntp"
  version = "~0.2.0"

[[constraint]]
  name = "github.com/cihub/seelog"
  version = "=v2.6"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "~3.2.0"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "~v0.2.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "~v1.13.1"

[[constraint]]
  name = "github.com/containerd/containerd"
  version = "~v1.2.2"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "~v1.0.0"

[[override]]
  name = "github.com/kubernetes/apimachinery"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[override]]
  name = "github.com/kubernetes/client-go"
  branch = "release-8.0"

[[override]]
    name = "k8s.io/client-go"
    branch = "release-8.0"

[[override]]
  name = "github.com/kubernetes/api"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.11"

[[override]]
  name = "github.com/kubernetes/apiserver"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.11"

[[override]]
  name = "github.com/kubernetes/metrics"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/metrics"
  branch = "release-1.11"

[[override]]
  name = "github.com/kubernetes-incubator/custom-metrics-apiserver"
  revision = "85ebc283a57287a8fcb3ad4b488d633cd63ef7d8"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "~v1.6.1"

[[constraint]]
  name = "github.com/mholt/archiver"
  revision = "26cf5bb32d07aa4e8d0de15f56ce516f4641d7df"

[[constraint]]
  name = "github.com/kardianos/osext"
  revision = "ae77be60afb1dcacde03767a8c37337fad28ac14"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "~v2.1.0"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "^v2.18.12"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~v0.0.1"

[[override]]
  name = "github.com/json-iterator/go"
  version = "~1.1.4"

[[constraint]]
  name = "github.com/DataDog/viper"
  version = "~v1.7.0"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "~v16"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~v1.2.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "~v2.2.2"

[[constraint]]
  name = "gopkg.in/zorkian/go-datadog-api.v2"
  version = "~v2.12"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~v1.12.74"

[[constraint]]
  branch = "master"
  name = "github.com/lxn/win"

[[override]]
  name = "github.com/StackExchange/wmi"
  revision = "5d049714c4a64225c3c79a7cf7d02f7fb5b96338"

[[override]]
  name = "github.com/jhoonb/archivex"
  revision = "be4efa7ec0c38ab76d56037014c90d48d6b13037"

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"

[[constraint]]
  name = "github.com/clbanning/mxj"
  version = "1.8.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.11.2"

[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"

[[override]]
  name = "bitbucket.org/ww/goautoneg"
  source = "github.com/adjust/goautoneg"
  revision = "d788f35a0315672bc90f50a6145d1252a230ee0d"

[[override]]
  name = "github.com/spf13/cast"
  source = "github.com/DataDog/cast"
  revision = "1ee8c8bd14a3d768a7ff681617ed56bc6c204940"

[[constraint]]
  name = "github.com/DataDog/gopsutil"
  revision = "aea6a47ff66c0ded148f385a8276d74321d8fc1a"

[[constraint]]
  name = "github.com/iovisor/gobpf"
  revision = "98ebf56442afb10e1b43145127de3c1777ed7e95"

[[constraint]]
  name = "github.com/florianl/go-conntrack"
  revision = "6d50e184fe3ef7ba0640303db5e6a5610bf4a297"

[[override]]
  name = "golang.org/x/sys"
  revision = "61b9204099cb1bebc803c9ffb9b2d3acd9d457d9"
