---
# Windows installer script deployment for e2e tests
qa_installer_script_windows:
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/gitlab_agent_deploy$CI_IMAGE_GITLAB_AGENT_DEPLOY_SUFFIX:$CI_IMAGE_GITLAB_AGENT_DEPLOY
  stage: deploy_packages
  tags: ["arch:amd64", "specific:true"]
  rules:
    - !reference [.on_installer_or_e2e_changes]
    - !reference [.manual]
  needs:
    - powershell_script_signing
  before_script:
    - ls $WINDOWS_POWERSHELL_DIR
  script:
    - $S3_CP_CMD $WINDOWS_POWERSHELL_DIR/Install-Datadog.ps1 s3://${INSTALLER_TESTING_S3_BUCKET}/pipeline-${CI_PIPELINE_ID}/scripts/Install-Datadog.ps1
