---
include:
  - .gitlab/.pre/common/container_publish_job_templates.yml

.dev_a7-windows-common:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  needs:
    - docker_build_agent7_windows
  variables:
    IMG_REGISTRIES: dev
  parallel:
    matrix:
      # Multi-arch
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7"
        IMG_SOURCES: "%BASE%-win1809-amd64,%BASE%-winltsc2022-amd64,%BASE%-winltsc2025-amd64"
        IMG_DESTINATIONS: agent-dev:${IMG_DESTINATION_SLUG}-py3-win
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx"
        IMG_SOURCES: "%BASE%-win1809-amd64,%BASE%-winltsc2022-amd64,%BASE%-winltsc2025-amd64"
        IMG_DESTINATIONS: agent-dev:${IMG_DESTINATION_SLUG}-py3-jmx-win
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7"
        IMG_SOURCES: "%BASE%-win1809-servercore-amd64,%BASE%-winltsc2022-servercore-amd64,%BASE%-winltsc2025-servercore-amd64"
        IMG_DESTINATIONS: agent-dev:${IMG_DESTINATION_SLUG}-py3-win-servercore
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx"
        IMG_SOURCES: "%BASE%-win1809-servercore-amd64,%BASE%-winltsc2022-servercore-amd64,%BASE%-winltsc2025-servercore-amd64"
        IMG_DESTINATIONS: agent-dev:${IMG_DESTINATION_SLUG}-py3-jmx-win-servercore
      # ltsc2019
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7"
        IMG_SOURCES: "%BASE%-win1809-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-win-ltsc2019
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx"
        IMG_SOURCES: "%BASE%-win1809-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-jmx-win-ltsc2019
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7"
        IMG_SOURCES: "%BASE%-win1809-servercore-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-win-servercore-ltsc2019
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx"
        IMG_SOURCES: "%BASE%-win1809-servercore-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-jmx-win-servercore-ltsc2019
      # ltsc2022
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7"
        IMG_SOURCES: "%BASE%-winltsc2022-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-win-ltsc2022
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx"
        IMG_SOURCES: "%BASE%-winltsc2022-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-jmx-win-ltsc2022
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7"
        IMG_SOURCES: "%BASE%-winltsc2022-servercore-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-win-servercore-ltsc2022
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx"
        IMG_SOURCES: "%BASE%-winltsc2022-servercore-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-jmx-win-servercore-ltsc2022
      # ltsc2025
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7"
        IMG_SOURCES: "%BASE%-winltsc2025-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-win-ltsc2025
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx"
        IMG_SOURCES: "%BASE%-winltsc2025-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-jmx-win-ltsc2025
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7"
        IMG_SOURCES: "%BASE%-winltsc2025-servercore-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-win-servercore-ltsc2025
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx"
        IMG_SOURCES: "%BASE%-winltsc2025-servercore-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-jmx-win-servercore-ltsc2025

dev_branch-a7-windows:
  extends: .dev_a7-windows-common
  rules:
    !reference [.manual]
  variables:
    IMG_DESTINATION_SLUG: ${CI_COMMIT_REF_SLUG}

dev_master-a7-windows:
  extends: .dev_a7-windows-common
  rules:
    !reference [.on_main]
  variables:
    IMG_DESTINATION_SLUG: master

dev_nightly-a7-windows:
  extends: .dev_a7-windows-common
  rules:
    !reference [.on_deploy_nightly_repo_branch]
  variables:
    IMG_DESTINATION_SLUG: nightly

.dev_fips-a7-windows-common:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  needs:
    - docker_build_fips_agent7_windows
  variables:
    IMG_REGISTRIES: dev
  # Only publish ltsc2022 servercore for now, that's all that's used by the integrations testing
  parallel:
    matrix:
      # ltsc2022
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips"
        IMG_SOURCES: "%BASE%-winltsc2022-servercore-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-fips-win-servercore-ltsc2022
      - IMG_VARIABLES: "BASE=${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-jmx"
        IMG_SOURCES: "%BASE%-winltsc2022-servercore-amd64"
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-fips-jmx-win-servercore-ltsc2022

dev_branch-fips-a7-windows:
  extends: .dev_fips-a7-windows-common
  rules:
    !reference [.manual]
  variables:
    IMG_DESTINATION_SLUG: ${CI_COMMIT_REF_SLUG}

dev_master-fips-a7-windows:
  extends: .dev_fips-a7-windows-common
  rules:
    !reference [.on_main]
  variables:
    IMG_DESTINATION_SLUG: master

dev_nightly-fips-a7-windows:
  extends: .dev_fips-a7-windows-common
  rules:
    !reference [.on_deploy_nightly_repo_branch]
  variables:
    IMG_DESTINATION_SLUG: nightly
