---
include:
  - .gitlab/.pre/common/container_publish_job_templates.yml

dev_branch-dogstatsd:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.manual]
  needs:
    - docker_build_dogstatsd_amd64
    - docker_build_dogstatsd_arm64
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_DSD}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64,${SRC_DSD}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64
    IMG_DESTINATIONS: dogstatsd-dev:${CI_COMMIT_REF_SLUG}

dev_branch_multiarch-a7:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.manual]
  needs:
    - docker_build_agent7
    - docker_build_agent7_arm64
    - docker_build_agent7_jmx
    - docker_build_agent7_jmx_arm64
  variables:
    IMG_REGISTRIES: dev
  parallel:
    matrix:
      - IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-arm64
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3
      - IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-arm64
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-py3-jmx
      - IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-arm64
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_SHORT_SHA}-py3-jmx

dev_branch_multiarch-fips:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.manual]
  needs:
    - docker_build_fips_agent7
    - docker_build_fips_agent7_arm64
    - docker_build_fips_agent7_jmx
    - docker_build_fips_agent7_arm64_jmx
  variables:
    IMG_REGISTRIES: dev
  parallel:
    matrix:
      - IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-arm64
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-fips
      - IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-jmx-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-jmx-arm64
        IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-fips-jmx

dev_branch_multiarch-dogstatsd:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.manual]
  needs:
    - docker_build_dogstatsd_amd64
    - docker_build_dogstatsd_arm64
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_DSD}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64,${SRC_DSD}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64
    IMG_DESTINATIONS: dogstatsd-dev:${CI_COMMIT_REF_SLUG}

dev_master-a7:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.on_main]
  needs:
    - docker_build_agent7
    - docker_build_agent7_arm64
    - docker_build_agent7_jmx
    - docker_build_agent7_jmx_arm64
  variables:
    IMG_REGISTRIES: dev
  parallel:
    matrix:
      - IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-arm64
        IMG_DESTINATIONS: agent-dev:master-py3
      - IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-arm64
        IMG_DESTINATIONS: agent-dev:master-py3-jmx

dev_master-fips:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.on_main]
  needs:
    - docker_build_fips_agent7
    - docker_build_fips_agent7_arm64
    - docker_build_fips_agent7_jmx
    - docker_build_fips_agent7_arm64_jmx
  variables:
    IMG_REGISTRIES: dev
  parallel:
    matrix:
      - IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-arm64
        IMG_DESTINATIONS: agent-dev:master-fips
      - IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-jmx-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-jmx-arm64
        IMG_DESTINATIONS: agent-dev:master-fips-jmx

dev_master-dogstatsd:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.on_main]
  needs:
    - docker_build_dogstatsd_amd64
    - docker_build_dogstatsd_arm64
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_DSD}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64,${SRC_DSD}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64
    IMG_DESTINATIONS: dogstatsd-dev:master

dca_dev_branch:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.manual]
  needs:
    - docker_build_cluster_agent_amd64
    - docker_build_cluster_agent_arm64
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_DCA}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64,${SRC_DCA}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64
    IMG_DESTINATIONS: cluster-agent-dev:${CI_COMMIT_REF_SLUG}

dca_dev_master:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.on_main]
  needs:
    - docker_build_cluster_agent_amd64
    - docker_build_cluster_agent_arm64
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_DCA}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64,${SRC_DCA}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64
    IMG_DESTINATIONS: cluster-agent-dev:master

cws_instrumentation_dev_branch_multiarch:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.manual]
  needs:
    - docker_build_cws_instrumentation_amd64
    - docker_build_cws_instrumentation_arm64
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_CWS_INSTRUMENTATION}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64,${SRC_CWS_INSTRUMENTATION}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64
    IMG_DESTINATIONS: cws-instrumentation-dev:${CI_COMMIT_REF_SLUG}

# deploys nightlies to agent-dev
dev_nightly-a7:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.on_deploy_nightly_repo_branch]
  needs:
    - docker_build_agent7
    - docker_build_agent7_arm64
    - docker_build_agent7_jmx
    - docker_build_agent7_jmx_arm64
  variables:
    IMG_REGISTRIES: dev
  parallel:
    matrix:
      - IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-arm64
        IMG_DESTINATIONS: agent-dev:nightly-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-py3,agent-dev:nightly-${CI_COMMIT_REF_SLUG}-py3
      - IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-arm64
        IMG_DESTINATIONS: agent-dev:nightly-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-py3-jmx,agent-dev:nightly-${CI_COMMIT_REF_SLUG}-py3-jmx

dev_nightly-a7-full:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.on_deploy_nightly_repo_branch]
  needs:
    - docker_build_agent7_full
    - docker_build_agent7_full_arm64
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-full-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-full-arm64
    IMG_DESTINATIONS: agent-dev:nightly-full-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-jmx,agent-dev:nightly-full-${CI_COMMIT_REF_SLUG}-jmx

# deploys nightlies to agent-dev
dev_nightly-dogstatsd:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules: !reference [.on_deploy_nightly_repo_branch]
  needs:
    - docker_build_dogstatsd_amd64
    - docker_build_dogstatsd_arm64
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_DSD}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64,${SRC_DSD}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64
    IMG_DESTINATIONS: dogstatsd-dev:nightly-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA},dogstatsd-dev:nightly-${CI_COMMIT_REF_SLUG}

dev_branch-full:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.manual]
  needs:
    - docker_build_agent7_full
    - docker_build_agent7_full_arm64
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-full-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-full-arm64
    IMG_DESTINATIONS: agent-dev:${CI_COMMIT_REF_SLUG}-full,agent-dev:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-full

dev_branch-ot-standalone:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.manual]
  needs:
    - docker_build_ot_agent_standalone_amd64
    - docker_build_ot_agent_standalone_arm64
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_OTEL_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-amd64,${SRC_OTEL_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-arm64
    IMG_DESTINATIONS: otel-agent-dev:${CI_COMMIT_REF_SLUG}-7

dev_nightly-host-profiler-standalone:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.on_deploy_nightly_repo_branch]
  needs:
    - docker_build_host_profiler_standalone_amd64
    - docker_build_host_profiler_standalone_arm64
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_DDOT_EBPF}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-amd64,${SRC_DDOT_EBPF}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-arm64
    IMG_DESTINATIONS: ddot-ebpf-dev:nightly-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA},ddot-ebpf-dev:nightly-${CI_COMMIT_REF_SLUG},ddot-ebpf-dev:nightly-latest

.publish_host_profiler_base:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  needs:
    - job: docker_build_host_profiler_standalone_amd64
      optional: true
    - job: docker_build_host_profiler_standalone_arm64
      optional: true
  before_script:
    - |
      if [ "${DEVTEST:-}" = "1" ]; then
        export IMG_DESTINATIONS="ddot-ebpf-dev:devtest-latest"
      else
        export IMG_DESTINATIONS="ddot-ebpf-dev:${CI_COMMIT_REF_SLUG}"
      fi
  variables:
    IMG_REGISTRIES: dev
    IMG_SOURCES: ${SRC_DDOT_EBPF}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-amd64,${SRC_DDOT_EBPF}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-arm64

dev_branch-host-profiler-standalone:
  extends: .publish_host_profiler_base
  rules:
    - when: manual
      allow_failure: true

dev_deploy-host-profiler-devtest:
  extends: .publish_host_profiler_base
  rules:
    - when: manual
      allow_failure: true
  variables:
    DEVTEST: "1"

.trigger_relenv_base:
  stage: dev_container_deploy
  trigger:
    project: DataDog/apm-reliability/datadog-reliability-env
  variables:
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME
    UPSTREAM_PROJECT_ID: $CI_PROJECT_ID
    UPSTREAM_PROJECT_NAME: ddot-ebpf-dev
    UPSTREAM_COMMIT_SHA: $CI_COMMIT_SHA

deploy_host_profiler_to_reliability_env_nightly:
  extends: .trigger_relenv_base
  rules:
    - !reference [.on_deploy_nightly_repo_branch]
  needs:
    - dev_nightly-host-profiler-standalone
  trigger:
    branch: master

deploy_host_profiler_to_reliability_env_devtest:
  extends: .trigger_relenv_base
  rules:
    - when: on_success
  needs:
    - dev_deploy-host-profiler-devtest
  trigger:
    branch: theomagellan/add-host-profiler
