# Jobs that deploy agent images on agent-qa ECR, to be used by e2e tests

qa_agent:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.except_mergequeue]
    - !reference [.except_disable_e2e_tests]
    - when: on_success
  needs:
    - docker_build_agent7
    - docker_build_agent7_arm64
    - job: docker_build_agent7_windows
      optional: true
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-arm64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-win1809-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-winltsc2022-amd64
    IMG_DESTINATIONS: agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}

qa_agent_fips:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.except_mergequeue]
    - !reference [.except_disable_e2e_tests]
    - when: on_success
  needs:
    - docker_build_fips_agent7
    - docker_build_fips_agent7_arm64
    - job: docker_build_fips_agent7_windows
      optional: true
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-arm64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-winltsc2022-servercore-amd64
    IMG_DESTINATIONS: agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-fips

qa_agent_jmx:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.except_mergequeue]
    - !reference [.except_disable_e2e_tests]
    - when: on_success
  needs:
    - docker_build_agent7_jmx
    - docker_build_agent7_jmx_arm64
    - job: docker_build_agent7_windows
      optional: true
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-arm64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-win1809-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-winltsc2022-amd64
    IMG_DESTINATIONS: agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-jmx

qa_agent_fips_jmx:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.except_mergequeue]
    - !reference [.except_disable_e2e_tests]
    - when: on_success
  needs:
    - docker_build_fips_agent7_jmx
    - docker_build_fips_agent7_arm64_jmx
    - job: docker_build_fips_agent7_windows
      optional: true
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-jmx-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-jmx-arm64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-jmx-winltsc2022-servercore-amd64
    IMG_DESTINATIONS: agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-fips-jmx

# Linux-only variants for e2e tests that don't require Windows images.
# These unblock container-based tests ~20 minutes earlier by not waiting for Windows builds.
qa_agent_linux:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.except_mergequeue]
    - !reference [.except_disable_e2e_tests]
    - when: on_success
  needs:
    - docker_build_agent7
    - docker_build_agent7_arm64
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-arm64
    IMG_DESTINATIONS: agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-linux

qa_agent_fips_linux:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.except_mergequeue]
    - !reference [.except_disable_e2e_tests]
    - when: on_success
  needs:
    - docker_build_fips_agent7
    - docker_build_fips_agent7_arm64
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-arm64
    IMG_DESTINATIONS: agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-fips-linux

qa_agent_linux_jmx:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.except_mergequeue]
    - !reference [.except_disable_e2e_tests]
    - when: on_success
  needs:
    - docker_build_agent7_jmx
    - docker_build_agent7_jmx_arm64
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-jmx-arm64
    IMG_DESTINATIONS: agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-linux-jmx

qa_agent_fips_linux_jmx:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.except_mergequeue]
    - !reference [.except_disable_e2e_tests]
    - when: on_success
  needs:
    - docker_build_fips_agent7_jmx
    - docker_build_fips_agent7_arm64_jmx
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-jmx-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-fips-jmx-arm64
    IMG_DESTINATIONS: agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-fips-linux-jmx

qa_agent_full:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.on_otel_or_e2e_changes]
    - !reference [.manual]
  needs:
    - docker_build_agent7_full
    - docker_build_agent7_full_arm64
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-full-amd64,${SRC_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-full-arm64
    IMG_DESTINATIONS: agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-full

qa_ot_agent_standalone:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.on_otel_or_e2e_changes]
    - !reference [.manual]
  needs:
    - docker_build_ot_agent_standalone_amd64
    - docker_build_ot_agent_standalone_arm64
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_OTEL_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-amd64,${SRC_OTEL_AGENT}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-7-arm64
    IMG_DESTINATIONS: otel-agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}

qa_dca:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.except_mergequeue]
    - !reference [.except_disable_e2e_tests]
    - when: on_success
  needs:
    - docker_build_cluster_agent_amd64
    - docker_build_cluster_agent_arm64
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_DCA}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64,${SRC_DCA}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64
    IMG_DESTINATIONS: cluster-agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}

qa_dca_fips:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.except_mergequeue]
    - !reference [.except_disable_e2e_tests]
    - when: on_success
  needs:
    - docker_build_cluster_agent_fips_arm64
    - docker_build_cluster_agent_fips_amd64
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_DCA}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-fips-amd64,${SRC_DCA}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-fips-arm64
    IMG_DESTINATIONS: cluster-agent-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-fips

qa_dogstatsd:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  rules:
    - !reference [.except_mergequeue]
    - !reference [.except_disable_e2e_tests]
    - when: on_success
  needs:
    - docker_build_dogstatsd_amd64
    - docker_build_dogstatsd_arm64
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_DSD}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64,${SRC_DSD}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64
    IMG_DESTINATIONS: dogstatsd-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}

.qa_cws_instrumentation:
  extends: .docker_publish_job_definition
  stage: dev_container_deploy
  needs:
    - docker_build_cws_instrumentation_amd64
    - docker_build_cws_instrumentation_arm64
  variables:
    IMG_REGISTRIES: agent-qa
    IMG_SOURCES: ${SRC_CWS_INSTRUMENTATION}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64,${SRC_CWS_INSTRUMENTATION}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64
    IMG_DESTINATIONS: cws-instrumentation-qa:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}

qa_cws_instrumentation:
  extends: .qa_cws_instrumentation
  rules:
    - !reference [.on_cws_or_e2e_changes]
    - !reference [.manual]
