# declare ConfigMap as a resource
resources:
  - cluster-agent-rbac.yaml
  - cluster-agent-auth-token.yaml
  - cluster-agent-config-map.yaml
  - cluster-agent.yaml
  - agent-rbac.yaml
  - agent-config-map.yaml
  - agent.yaml
