---

trigger_distribution:
  stage: trigger_distribution
  rules: !reference [.on_deploy_success]
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include:
      - local: .gitlab/distribution.yml
    forward:
      pipeline_variables: true

trigger_distribution_on_failure:
  stage: trigger_distribution
  needs: []
  rules: !reference [.on_deploy_manual]
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include:
      - local: .gitlab/distribution.yml
    forward:
      pipeline_variables: true
