---
.docker_build_agent_windows_common:
  stage: container_build
  id_tokens:
    CI_IDENTITY_GITLAB_JWT:
      aud: https://vault.us1.ddbuild.io
  variables:
    IMAGE: registry.ddbuild.io/ci/datadog-agent/agent
    BUILD_CONTEXT: Dockerfiles/agent
    CI_IDENTITY_ROLE_NAME_OVERRIDE: windows-ci-tmp-gitlab-id-token-datadog-agent-all-refs
  script:
    - $ECR_RELEASE_SUFFIX="$(If ($BUCKET_BRANCH -eq `"nightly`") { `"-nightly`" } elseif ($CI_COMMIT_TAG) { `"-release`" } else { `"`" })"
    - $TARGET_TAG="${IMAGE}${ECR_RELEASE_SUFFIX}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}${TAG_SUFFIX}-win${VARIANT}${SERVERCORE}-amd64"
    - $BUILD_DATE = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"
    - $ErrorActionPreference = "Stop"
    - cp ${OMNIBUS_PACKAGE_DIR}/pipeline-${CI_PIPELINE_ID}/${AGENT_ZIP} ${BUILD_CONTEXT}/datadog-agent-latest.amd64.zip
    - cp entrypoint.exe ${BUILD_CONTEXT}/entrypoint.exe

    - pushd ${BUILD_CONTEXT}
    - |
      & 'C:\Program Files\7-Zip\7z.exe' x .\datadog-agent-latest.amd64.zip -o"Datadog Agent"
    - Remove-Item datadog-agent-latest.amd64.zip
    # Omnibus uses a slightly different path than the actual install
    # TODO: This overwrites an extra agent.exe, we should also remove it from the zip
    - mv "Datadog Agent\bin\agent\agent.exe" "Datadog Agent\bin\agent.exe" -Force
    - mv "Datadog Agent\bin\agent\secret-generic-connector.exe" "Datadog Agent\bin\secret-generic-connector.exe" -Force
    - popd

    - get-childitem ${BUILD_CONTEXT}
    - >
      powershell -Command "$(Get-Location)\tools\ci\retry.ps1
      docker build
      --no-cache
      --build-arg CI
      --build-arg GENERAL_ARTIFACTS_CACHE_BUCKET_URL=${GENERAL_ARTIFACTS_CACHE_BUCKET_URL}
      ${BUILD_ARG}
      --pull
      --file ${BUILD_CONTEXT}/windows/amd64/Dockerfile
      --tag ${TARGET_TAG}
      --label 'org.opencontainers.image.created=${BUILD_DATE}'
      --label 'org.opencontainers.image.version=${AGENT_VERSION}'
      --label 'org.opencontainers.image.revision=${CI_COMMIT_SHA}'
      ${BUILD_CONTEXT}"
    - If ($lastExitCode -ne "0") { throw "Previous command returned $lastExitCode" }
    - powershell -Command "$(Get-Location)\tools\ci\retry.ps1 docker push ${TARGET_TAG}"
    - If ($lastExitCode -ne "0") { throw "Previous command returned $lastExitCode" }
    - docker rmi ${TARGET_TAG}
    - If ($lastExitCode -ne "0") { throw "Previous command returned $lastExitCode" }
  timeout: 60m

# Base template for agent7 windows builds
.docker_build_agent7_windows_common:
  extends:
    - .docker_build_agent_windows_common
  rules:
    - !reference [.except_mergequeue]
    - when: on_success
  needs:
    ["setup_agent_version", "windows_msi_and_bosh_zip_x64-a7", "build_windows_container_entrypoint"]
  variables:
    AGENT_ZIP: "datadog-agent-7*-x86_64.zip"
    SERVERCORE: ""  # Default to nanoserver (empty), override to "-servercore" for servercore builds
    # OS_TYPE should be set to "nano" or "core" in the job
    # OS_DISPLAY_NAME should be "windows nanoserver" or "windows server core"
    BUILD_ARG: "--build-arg BASE_IMAGE=${SERVER_BASE_IMAGE} --build-arg BASE_IMAGE_OS='${OS_DISPLAY_NAME}' --build-arg WITH_JMX=${WITH_JMX} --build-arg VARIANT=${VARIANT} --build-arg INSTALL_INFO=${OS_TYPE}-${VARIANT}"
  retry: 2

# Base template for FIPS agent7 windows builds
.docker_build_fips_agent7_windows_common:
  extends:
    - .docker_build_agent_windows_common
  rules:
    - !reference [.except_mergequeue]
    - when: on_success
  needs:
    ["windows_msi_and_bosh_zip_x64-a7-fips", "build_windows_container_entrypoint"]
  variables:
    AGENT_ZIP: "datadog-fips-agent-7*-x86_64.zip"
    SERVERCORE: ""  # Default to nanoserver (empty), override to "-servercore" for servercore builds
    # OS_TYPE should be set to "nano" or "core" in the job
    # OS_DISPLAY_NAME should be "windows nanoserver" or "windows server core"
    BUILD_ARG: "--build-arg BASE_IMAGE=${SERVER_BASE_IMAGE} --build-arg BASE_IMAGE_OS='${OS_DISPLAY_NAME}' --build-arg WITH_JMX=${WITH_JMX} --build-arg WITH_FIPS=true --build-arg VARIANT=${VARIANT} --build-arg INSTALL_INFO=${OS_TYPE}-${VARIANT}-fips"
  retry: 2

include:
  - .gitlab/deploy/container_build/docker_windows_agent7.yml
