---
blank_issues_enabled: false
contact_links:
  - name: Bug Report (High Priority)
    url: https://help.datadoghq.com/hc/en-us/requests/new?tf_1260824651490=pt_product_type:agent
    about: Create an expedited Bug Report via the helpdesk (no login required). This will allow us to look up your account and allows you to provide additional information in private. Please do not create a GitHub issue to report a bug.
  - name: Feature Request (High Priority)
    url: https://help.datadoghq.com/hc/en-us/requests/new?tf_1260824651490=pt_product_type:agent&tf_4415956267547=pt_agent_category:feature_request
    about: Create an expedited Feature Request via the helpdesk (no login required). This helps with prioritization and allows you to provide additional information in private. Please do not create a GitHub issue to request a feature.