[package]
name = "sd-agent"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.91"

[lib]
name = "dd_discovery"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "sd-agent"
path = "src/main.rs"

[[bin]]
name = "disco"
path = "src/bin/disco.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0.98"
cap-std = "3.4"
http-body-util = "0.1"
hyper-util = { version = "0.1", default-features = false, features = ["http1", "server", "tokio"] }
hyper = { version = "1"} # hyper-utils adds the needed features, no need to define them here
log = "0.4"
lru = { version = "0.16.0", default-features = false }  # Don't use hashbrown for the hash map; prefer std
phf = { version = "0.11", features = ["macros"] }
rmp-serde = "1.3"
serde_json = "1.0"
serde = { version ="1.0.219", features = ["derive", "std"] }
simple_logger = { version = "5.0", features = ["colors", "timestamps"] }
thiserror = "2.0.12"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal"] }
uzers = "0.12"
elf = "0.8.0"
memchr = "2.7.6"
nom = "7.1"
zip = { version = "2.1", default-features = false, features = ["deflate"] }
glob-match = "0.2"
yaml-rust2 = "0.9"
normalize-path = "0.2"
walkdir = "2"
quick-xml = { version = "0.37", features = ["serialize"] }

[dev-dependencies]
memmap2 = "0.9"
scopeguard = "1.2"
tempfile = "3.0"
temp-env = "0.3"
dircpy = "0.3.19"
nix = { version = "0.29", features = ["signal"] }

[profile.release]
lto = "fat"
opt-level = "z"
strip = "symbols"
panic = "abort"
