---
.build_serverless_common:
  stage: binary_build
  rules:
    - !reference [.except_mergequeue]
    - when: on_success
  before_script:
    - !reference [.retrieve_linux_go_deps]
  script:
    - dda inv -- check-go-version
    - cd cmd/serverless && go build -ldflags="-w -s" -a -v -tags "serverless otlp" -o $BINARY_NAME

build_serverless-deb_x64:
  extends: .build_serverless_common
  variables:
    BINARY_NAME: datadog-agent-x64
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/linux-glibc-2-17-x64$CI_IMAGE_LINUX_GLIBC_2_17_X64_SUFFIX:$CI_IMAGE_LINUX_GLIBC_2_17_X64
  tags: ["arch:amd64-ci-test"]
  needs: ["go_deps"]
  artifacts:
    expire_in: 1 day
    paths:
      - $CI_PROJECT_DIR/cmd/serverless

build_serverless-deb_arm64:
  extends: .build_serverless_common
  variables:
    BINARY_NAME: datadog-agent-arm64
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/linux-glibc-2-23-arm64$CI_IMAGE_LINUX_GLIBC_2_23_ARM64_SUFFIX:$CI_IMAGE_LINUX_GLIBC_2_23_ARM64
  tags: ["arch:arm64"]
  needs: ["go_deps"]
