[package]
name = "dd-procmgrd"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "dd-procmgrd"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
log.workspace = true
nix = { workspace = true, features = ["signal", "process"] }
serde = { workspace = true, features = ["derive"] }
serde_yaml.workspace = true
simple_logger = { workspace = true, features = ["timestamps"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "process", "fs", "time", "sync"] }

[dev-dependencies]
nix = { workspace = true, features = ["signal", "process", "user"] }
tempfile.workspace = true