[package]
name = "httpcheck"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../../core" }
rustls = "0.23.29"
webpki-roots = "1.0.1"
x509-parser = "0.17.0"

[lib]
crate-type = ["cdylib"]
