---
deploy_cluster_agent_cloudfoundry:
  rules:
    !reference [.on_deploy]
  stage: deploy_packages
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/gitlab_agent_deploy$CI_IMAGE_GITLAB_AGENT_DEPLOY_SUFFIX:$CI_IMAGE_GITLAB_AGENT_DEPLOY
  tags: ["arch:amd64", "specific:true"]
  needs: ["cluster_agent_cloudfoundry-build_amd64"]
  before_script:
    - ls $OMNIBUS_PACKAGE_DIR
  script:
    - $S3_CP_CMD --recursive --exclude "*" --include "datadog-cluster-agent-cloudfoundry-*.tar.xz" $OMNIBUS_PACKAGE_DIR $S3_DSD6_URI/linux/cluster-agent-cloudfoundry/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers full=id=3a6e02b08553fd157ae3fb918945dd1eaae5a1aa818940381ef07a430cf25732
