---
include:
  - .gitlab/.pre/common/container_publish_job_templates.yml

.deploy_packages_oci:
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/gitlab_agent_deploy$CI_IMAGE_GITLAB_AGENT_DEPLOY_SUFFIX:$CI_IMAGE_GITLAB_AGENT_DEPLOY
  tags: ["arch:amd64", "specific:true"]
  stage: deploy_packages
  rules:
    - !reference [.on_deploy]
    - !reference [.on_deploy_installer]
    - !reference [.on_installer_or_e2e_changes]
    - !reference [.manual]
  before_script:
    - ls $OMNIBUS_PACKAGE_DIR
  script:
    - set +x
    - !reference [.retrieve_linux_go_tools_deps]
    - VERSION="$(dda inv agent.version --url-safe)-1" || exit $?
    - VERSION_NO_PIPELINE="$(dda inv agent.version --url-safe | sed -E 's/\.pipeline(.*)//')-1" || exit $?
    - datadog-package push registry.ddbuild.io/ci/remote-updates/${OCI_PRODUCT}:${VERSION} ${OMNIBUS_PACKAGE_DIR}/${OCI_PRODUCT}-${VERSION}.oci.tar
    # This is used for E2E tests. Doesn't cost more than an additional tag to the registry.
    - datadog-package push registry.ddbuild.io/ci/remote-updates/${OCI_PRODUCT}:pipeline-${CI_PIPELINE_ID} ${OMNIBUS_PACKAGE_DIR}/${OCI_PRODUCT}-${VERSION}.oci.tar
    # Used for e2e tests
    - datadog-package replicate-s3 registry.ddbuild.io/ci/remote-updates/${OCI_PRODUCT}:pipeline-${CI_PIPELINE_ID} us-east-1 ${INSTALLER_TESTING_S3_BUCKET} ${S3_PACKAGE} ${VERSION}
    - datadog-package replicate-s3 registry.ddbuild.io/ci/remote-updates/${OCI_PRODUCT}:pipeline-${CI_PIPELINE_ID} us-east-1 ${INSTALLER_TESTING_S3_BUCKET} ${S3_PACKAGE} ${VERSION_NO_PIPELINE}
    - datadog-package replicate-s3 registry.ddbuild.io/ci/remote-updates/${OCI_PRODUCT}:pipeline-${CI_PIPELINE_ID} us-east-1 ${INSTALLER_TESTING_S3_BUCKET} ${S3_PACKAGE} ${CI_COMMIT_SHA}
    - datadog-package replicate-s3 registry.ddbuild.io/ci/remote-updates/${OCI_PRODUCT}:pipeline-${CI_PIPELINE_ID} us-east-1 ${INSTALLER_TESTING_S3_BUCKET} ${S3_PACKAGE} pipeline-${CI_PIPELINE_ID}

deploy_agent_oci:
  extends: ".deploy_packages_oci"
  needs: [ "agent_oci", "go_tools_deps"]
  variables:
    OCI_PRODUCT: "datadog-agent"
    S3_PACKAGE: "agent-package"

deploy_installer_oci:
  extends: ".deploy_packages_oci"
  needs: [ "installer_oci", "go_tools_deps" ]
  variables:
    OCI_PRODUCT: "datadog-installer"
    S3_PACKAGE: "installer-package"

deploy_ddot_oci:
  extends: ".deploy_packages_oci"
  needs: [ "ddot_oci", "go_tools_deps" ]
  variables:
    OCI_PRODUCT: "datadog-agent-ddot"
    S3_PACKAGE: "ddot-package"
