[package]
name = "dd-procmgr"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.9", features = ["transport"] }
prost = "0.11"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
tower = "0.4"
colored = "2.0.4"
tabwriter = "1.3.0"
chrono = "0.4.31"

[build-dependencies]
tonic-build = "0.9"
