global_config_source = "aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0RhdGFEb2cvZ2l0aHViLW1ldGFkYXRhL21hc3Rlci9qaXJhLnRvbWw="
qa_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
ignored_labels = [
  "qa/skip-qa",
]

[teams."Agent Metrics Logs"]
jira_project = "AMLII"
jira_issue_type = "Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "agent-metrics-logs"
github_labels = ["team/agent-metrics-logs"]
exclude_members = ["olivielpeau"]

[teams."Agent Shared Components"]
jira_project = "ASCII"
jira_issue_type = "QA"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "agent-shared-components"
github_labels = ["team/agent-shared-components"]
exclude_members = ["olivielpeau", "sgnn7"]

[teams."Agent Platform"]
jira_project = "APL"
jira_issue_type = "QA"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "agent-platform"
github_labels = ["team/agent-platform"]
exclude_members = ["olivielpeau"]

[teams."Universal Service Monitoring"]
jira_project = "USMON"
jira_issue_type = "Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "universal-service-monitoring"
github_labels = ["team/usm"]

[teams."Network Device Monitoring"]
jira_project = "NDMII"
jira_issue_type = "Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "network-device-monitoring"
github_labels = ["team/network-device-monitoring"]

[teams."Network Performance Monitoring"]
jira_project = "NPM"
jira_issue_type = "Task"
jira_statuses = [
  "Backlog",
  "In Progress",
  "Done",
]
github_team = "networks"
github_labels = ["team/networks"]

[teams."OpenTelemetry"]
jira_project = "OTEL"
jira_issue_type = "Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "opentelemetry"
github_labels = ["team/opentelemetry"]

[teams."eBPF Platform"]
jira_project = "EBPF"
jira_issue_type = "Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "ebpf-platform"
github_labels = ["team/ebpf-platform"]

[teams."Agent Integrations"]
jira_project = "AI"
jira_issue_type = "Task"
jira_statuses = [
  "Backlog",
  "In Progress",
  "Done",
]
github_team = "agent-integrations"
github_labels = ["team/integrations"]
exclude_members = [
  "hithwen",
]

[teams."Platform Integrations"]
jira_project = "PLINT"
jira_issue_type = "Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "platform-integrations"
github_labels = ["team/platform-integrations"]
exclude_members = [
  "hithwen",
]

[teams."APM"]
jira_project = "AIT"
jira_component = "Trace Agent"
jira_issue_type = "Task"
jira_statuses = [
  "Backlog",
  "In Progress",
  "Done",
]
github_team = "apm-go"
github_labels = ["team/agent-apm"]

[teams."Remote Config"]
jira_project = "RC"
jira_issue_type = "QA"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "remote-config"
github_labels = ["team/remote-config"]

[teams."Container Integrations"]
jira_project = "CONTINT"
jira_issue_type = "Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "container-integrations"
github_labels = ["team/containers"]
exclude_members = ["vboulineau"]

[teams."Container Ecosystems"]
jira_project = "CECO"
jira_issue_type = "Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "container-ecosystems"
github_labels = ["team/container-ecosystems"]

[teams."Security And Compliance Agent"]
jira_project = "SEC"
jira_component = "CWS Agent"
jira_issue_type = "Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "agent-security"
github_labels = ["team/agent-security"]

[teams."CSPM Agent"]
jira_project = "SEC"
jira_component = "CSPM Agent"
jira_issue_type = "Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "agent-cspm"
github_labels = ["team/agent-cspm"]

[teams."Processes"]
jira_project = "PROCS"
jira_issue_type = "Task"
jira_statuses = [
  "TRIAGE",
  "In Progress",
  "Done",
]
github_team = "processes"
github_labels = ["team/processes"]

[teams."Windows Agent"]
jira_project = "WINA"
jira_issue_type = "QA Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "windows-agent"
github_labels = ["team/windows-agent"]

[teams."Windows Kernel Integrations"]
jira_project = "WKINT"
jira_issue_type = "Task"
jira_statuses = [
  "To Do",
  "In Progress",
  "Done",
]
github_team = "windows-kernel-integrations"
github_labels = ["team/windows-kernel-integrations"]

[teams."Database Monitoring"]
jira_project = "DBMON"
jira_issue_type = "Task"
jira_statuses = [
  "Eventually",
  "In Progress",
  "Done",
]
github_team = "database-monitoring"
github_labels = ["team/database-monitoring"]

[teams."Container App"]
jira_project = "CAP2"
jira_issue_type = "Task"
jira_statuses = [
  "ðŸ’¼ To Do",
  "ðŸ’¡ In Progress",
  "âœ… Done",
]
github_team = "container-app"
github_labels = ["team/container-app"]

[teams."APM Onboarding"]
jira_project = "APMON"
jira_issue_type = "Task"
jira_statuses = [
  "Selected For Development",
  "In Progress",
  "Done",
]
github_team = "apm-onboarding"
github_labels = ["team/apm-onboarding"]
