global_config_source = "aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0RhdGFEb2cvZ2l0aHViLW1ldGFkYXRhL21hc3Rlci9qaXJhLnRvbWw="
qa_statuses = ["To Do", "In Progress", "Done"]
ignored_labels = ["qa/done", "qa/no-code-change"]

[teams."Agent Log Pipelines"]
jira_project = "AGNTLOG"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "agent-log-pipelines"
github_labels = ["team/agent-log-pipelines"]
exclude_members = [""]

[teams."Agent Metric Pipelines"]
jira_project = "AGTMETRICS"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "agent-metric-pipelines"
github_labels = ["team/agent-metric-pipelines"]
exclude_members = [""]

[teams."Agent Runtimes"]
jira_project = "AGENTRUN"
jira_issue_type = "QA"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "agent-runtimes"
github_labels = ["team/agent-runtimes"]
exclude_members = ["sgnn7", "cmourot"]

[teams."Agent Configuration"]
jira_project = "AGENTCFG"
jira_issue_type = "QA"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "agent-configuration"
github_labels = ["team/agent-configuration"]
exclude_members = ["sgnn7"]

[teams."Agent Developer Experience"]
jira_project = "ACIX"
jira_issue_type = "QA"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "agent-devx"
github_labels = ["team/agent-devx"]
exclude_members = []

[teams."Agent Delivery"]
jira_project = "BARX"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "agent-delivery"
github_labels = ["team/agent-delivery"]
exclude_members = ["KSerrania"]

[teams."Agent Build"]
jira_project = "ABLD"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "agent-build"
github_labels = ["team/agent-build"]

[teams."Agent Discovery"]
jira_project = "DSCVR"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "agent-discovery"
github_labels = ["team/agent-discovery"]

[teams."Universal Service Monitoring"]
jira_project = "USMON"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "universal-service-monitoring"
github_labels = ["team/usm"]

[teams."Network Device Monitoring - Core"]
jira_project = "NDMII"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "ndm-core"
github_labels = ["team/ndm-core", "team/network-device-monitoring"]
exclude_members = ["leeavital", "heyronhay"]

[teams."Network Device Monitoring - Integrations"]
jira_project = "NDINT"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "ndm-integrations"
github_labels = ["team/ndm-integrations"]
exclude_members = ["leeavital", "heyronhay"]

[teams."Network Performance Monitoring"]
jira_project = "NPM"
jira_issue_type = "Task"
jira_statuses = ["Backlog", "In Progress", "Done"]
github_team = "networks"
github_labels = ["team/networks"]

[teams."OpenTelemetry"]
jira_project = "OTEL"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "opentelemetry"
github_labels = ["team/opentelemetry"]
exclude_members = ["ancostas", "Maascamp"]

[teams."eBPF Platform"]
jira_project = "EBPF"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "ebpf-platform"
github_labels = ["team/ebpf-platform"]

[teams."Agent Integrations"]
jira_project = "AI"
jira_issue_type = "Task"
jira_statuses = ["Backlog", "In Progress", "Done"]
github_team = "agent-integrations"
github_labels = ["team/integrations"]
exclude_members = ["ofek", "alopezz"]

[teams."APM"]
jira_project = "APMSP"
jira_component = "Trace Agent"
jira_issue_type = "Task"
jira_statuses = ["Backlog", "In Progress", "Done"]
github_team = "agent-apm"
github_labels = ["team/agent-apm"]

[teams."Remote Config"]
jira_project = "RC"
jira_issue_type = "QA"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "remote-config"
github_labels = ["team/remote-config"]

[teams."Fleet Automation"]
jira_project = "FA"
jira_issue_type = "QA"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "Fleet"
github_labels = ["team/fleet-automation"]

[teams."Container Integrations"]
jira_project = "CONTINT"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "container-integrations"
github_labels = ["team/containers"]
exclude_members = ["clamoriniere"]

[teams."Container Platform"]
jira_project = "CONTP"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "container-platform"
github_labels = ["team/container-platform"]
exclude_members = ["clamoriniere"]

[teams."Container Ecosystems"]
jira_project = "CECO"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "container-ecosystems"
github_labels = ["team/container-ecosystems"]

[teams."Security And Compliance Agent"]
jira_project = "CWS"
jira_component = "Agent"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "agent-security"
github_labels = ["team/agent-security"]
exclude_members = [
  "jinroh",
  "0intro",
]

[teams."CSPM Agent"]
jira_project = "SEC"
jira_component = "CSPM Agent"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "agent-cspm"
github_labels = ["team/agent-cspm"]

[teams."Container Experiences"]
jira_project = "CXP"
jira_issue_type = "Task"
jira_statuses = ["TRIAGE", "In Progress", "Done"]
github_team = "container-experiences"
github_labels = ["team/container-experiences"]

[teams."Windows Agent"]
jira_project = "WINA"
jira_issue_type = "QA Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "windows-agent"
github_labels = ["team/windows-agent"]

[teams."Database Monitoring"]
jira_project = "DBMON"
jira_issue_type = "Task"
jira_statuses = ["Eventually", "In Progress", "Done"]
github_team = "database-monitoring"
github_labels = ["team/database-monitoring"]

[teams."Container App"]
jira_project = "CAP"
jira_issue_type = "Task"
jira_statuses = ["ðŸ’¼ To Do", "ðŸ’¡ In Progress", "âœ… Done"]
github_team = "container-app"
github_labels = ["team/container-app"]

[teams."APM Injection Platform"]
jira_project = "INPLAT"
jira_issue_type = "Task"
jira_statuses = ["Selected For Development", "In Progress", "Done"]
github_team = "injection-platform"
github_labels = ["team/injection-platform"]

[teams."Agent Release Management"]
jira_project = "AGNTR"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "agent-release-management"
github_labels = ["team/agent-release-management"]

[teams."Dynamic Instrumentation"]
jira_project = "DEBUG"
jira_component = "datadog-agent"
jira_issue_type = "Task"
jira_statuses = ["To Do", "In Progress", "Done"]
github_team = "debugger-go"
github_labels = ["team/dynamic-instrumentation"]
