apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: local-test

configMapGenerator:
- name: sts-agent-config
  behavior: merge
  literals:
     - STS_API_KEY=API_KEY
     - STS_STS_URL=http://34.254.41.209:7077/stsAgent
     - STS_PROCESS_AGENT_URL=http://34.254.41.209:7077/stsAgent
     - STS_APM_URL=http://34.254.41.209:7077/stsAgent
     - STS_CLUSTER_NAME=stackstate-demo-cluster
- name: sts-clusteragent-config
  behavior: merge
  literals:
     - STS_API_KEY=API_KEY
     - STS_STS_URL=http://34.254.41.209:7077/stsAgent
     - STS_CLUSTER_NAME=stackstate-demo-cluster

images:
  - name: docker.io/stackstate/stackstate-agent-test
    newTag: master
  - name: docker.io/stackstate/stackstate-cluster-agent-test
    newTag: master

secretGenerator:
- name: stackstate-auth-token
  # env is a path to a file to read lines of key=val
  # you can only specify one env file per secret.
  behavior: merge
  env: env.txt
  type: Opaque


# generatorOptions modify behavior of all ConfigMap and Secret generators
generatorOptions:
  disableNameSuffixHash: true
