####################################
## Runtime Security configuration ##
####################################

## @param runtime_security_config - custom object - optional
#
# runtime_security_config:

#   # @param enabled - boolean - optional - default: false
#   # Set to true to enable Cloud Workload Security (CWS).
#
#   enabled: false

{{ if (eq .OS "windows") }}
#   # @param socket - string - optional - default: localhost:3334
#   # The local address and port where the security runtime module is accessed
#
#   socket: localhost:3334
{{ else }}
#   # @param socket - string - optional - default: /opt/datadog-agent/run/runtime-security.sock
#   # The full path to the location of the unix socket where security runtime module is accessed.
#
#   socket: /opt/datadog-agent/run/runtime-security.sock
{{ end }}
