[workspace]
resolver = "3"
members = [
    "http_check/native",
    "http_check/shlib",
    "standalone",
]

[profile.release]
opt-level = "z"     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase
