docs:lint:
  stage: lint
  needs: []
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/linux$CI_IMAGE_LINUX_SUFFIX:$CI_IMAGE_LINUX
  tags: ["arch:amd64", "specific:true"]
  script:
    - echo "Linting docs $CLANG_LLVM_VER"
