[package]
name = "http_check"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
hyper-tls = "0.6"
bytes = "1"
tokio-native-tls = "0.3"
native-tls = "0.2"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
http = "1.3.1"
http-serde = "2.1.1"
thiserror = "2.0.17"
regex = "1.12.2"
x509-cert = "0.2"
libc = "0.2.178"
