# declare ConfigMap as a resource
resources:
  - cluster-agent-rbac.yaml
  - cluster-agent-auth-token.yaml
  - cluster-agent-config-map.yaml
  - cluster-agent-runner-config-maps.yaml
  - cluster-agent.yaml
  - agent-rbac.yaml
  - agent-integrations-config-map.yaml
  - agent-config-map.yaml
  - agent.yaml
  - kube-state-metrics.yaml
