test_and_lint_gitlab_configuration:
  stage: .pre
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/linux$CI_IMAGE_LINUX_SUFFIX:$CI_IMAGE_LINUX
  tags: ["arch:amd64", "specific:true"]
  needs: [compute_gitlab_ci_config]
  rules:
    - !reference [.on_dev_branches]
    - when: on_success
  script:
    - GITLAB_TOKEN=$($CI_PROJECT_DIR/tools/ci/fetch_secret.sh $GITLAB_TOKEN write_api) || exit $?; export GITLAB_TOKEN
    - dda inv -- -e linter.full-gitlab-ci --configs-or-diff-file artifacts/after.gitlab-ci.yml
    - dda inv -- -e linter.ssm-parameters

test_gitlab_compare_to:
  stage: .pre
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/linux$CI_IMAGE_LINUX_SUFFIX:$CI_IMAGE_LINUX
  tags: ["arch:amd64", "specific:true"]
  rules:
    - !reference [.except_mergequeue]
    - !reference [.on_gitlab_changes]
  script:
    - GITLAB_TOKEN=$($CI_PROJECT_DIR/tools/ci/fetch_secret.sh $GITLAB_TOKEN write_api) || exit $?; export GITLAB_TOKEN
    - !reference [.setup_agent_github_app]
    - dda self dep sync -f legacy-tasks
    - dda inv -- pipeline.compare-to-itself

# Computes and uploads the GitLab CI configuration diff as an artifact
compute_gitlab_ci_config:
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/linux$CI_IMAGE_LINUX_SUFFIX:$CI_IMAGE_LINUX
  stage: .pre
  needs: []
  tags: ["arch:arm64"]
  before_script:
    # Get main history
    - git fetch origin main
    - git checkout main
    - git checkout -
  script:
    - GITLAB_TOKEN=$($CI_PROJECT_DIR/tools/ci/fetch_secret.sh $GITLAB_TOKEN write_api) || exit $?; export GITLAB_TOKEN
    - mkdir -p artifacts
    - dda inv -- -e gitlab.compute-gitlab-ci-config --before-file artifacts/before.gitlab-ci.yml --after-file artifacts/after.gitlab-ci.yml --diff-file artifacts/diff.gitlab-ci.yml
  artifacts:
    when: always
    paths:
      - artifacts/
    expire_in: 1 day

lint_github_actions_shellcheck:
  stage: .pre
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/linux$CI_IMAGE_LINUX_SUFFIX:$CI_IMAGE_LINUX
  tags: ["arch:arm64"]
  needs: []
  rules:
    - !reference [.on_dev_branches]
    - changes:
        paths:
          - .github/workflows/**/*.yml
        compare_to: $COMPARE_TO_BRANCH
      when: on_success
  allow_failure: true
  script:
    - dda inv -- -e linter.github-actions-shellcheck
