---
name: Assess Repository Permissions

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Which permissions to assess: "repo" or "agent-all"'
        required: true
        default: 'repo'
        type: choice
        options:
          - repo
          - agent-all
  schedule:
    - cron: '0 4 2 * *' # At 4 UTC every 2nd day of the month (out of business hours for rate limiting)
    - cron: '0 6 2 * *' # Later for the simple permission display

permissions: {}

jobs:
  assess_repo_permission:
    runs-on: ubuntu-latest
    if: (github.event.schedule == '0 6 2 * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'repo'))
    strategy:
      matrix:
        value: ['datadog-agent', 'datadog-agent-buildimages', 'omnibus-ruby', 'agent-release-management']
      fail-fast: false
    environment:
      name: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .dda
            .github
            tasks
          persist-credentials: false

      - name: Install dda
        uses: ./.github/actions/install-dda
        with:
          features: legacy-tasks legacy-github

      - name: Assess Repository Permissions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_DATADOG_AGENT_BOT_TOKEN: ${{ secrets.SLACK_DATADOG_AGENT_BOT_TOKEN }}
        run: dda inv -- -e github.check-permissions --name ${{ matrix.value }} --check repo

  assess_agent_all_permission:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 4 2 * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'agent-all')
    environment:
      name: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .dda
            .github
            tasks
          persist-credentials: false

      - name: Install dda
        uses: ./.github/actions/install-dda
        with:
          features: legacy-tasks legacy-github

      - name: Assess agent-all Permissions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_DATADOG_AGENT_BOT_TOKEN: ${{ secrets.SLACK_DATADOG_AGENT_BOT_TOKEN }}
        run: dda inv -- -e github.check-permissions --name agent-all --check team
