---
name: Assess Repository Permissions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 2 * *' # At 5 UTC every 2nd day of the month (out of business hours for rate limiting)

permissions: {}

jobs:
    assess_permission:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            value: ['datadog-agent', 'datadog-agent-buildimages', 'datadog-agent-macos-build', 'omnibus-ruby', 'omnibus-software', 'agent-releaes']
          fail-fast: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
              with:
                sparse-checkout: 'tasks'
                persist-credentials: false

            - name: Install python
              uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
              with:
                python-version-file: .python-version
                cache: "pip"

            - name: Install Python dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install -r tasks/libs/requirements-github.txt

            - name: Assess Repository Permissions
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
              run: inv -e github.check-permissions --repo ${{ matrix.value }}
