---
name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]
  merge_group: # This is to skip this check on merge
    types: [checks_requested]


# GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  contents: read
  pull-requests: write
  id-token: write # Needed to federate tokens.
  actions: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        id: octo-sts
        with:
          scope: DataDog/cla-signatures
          policy: self.write-signatures-datadog-agent

      - name: "CLA Assistant"
        if: github.event_name != 'merge_group' && ((github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target')
        uses: contributor-assistant/github-action@ca4a40a7d1004f18d9960b404b97e5f30a505a08 # v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ steps.octo-sts.outputs.token }}
        with:
          path-to-signatures: 'datadog-agent.json'
          path-to-document: 'https://gist.github.com/bits-bot/55bdc97a4fdad52d97feb4d6c3d1d618' # e.g. a CLA or a DCO document
          branch: datadog-agent
          remote-repository-name: cla-signatures
          remote-organization-name: DataDog
          allowlist: "*[bot]"
          lock-pullrequest-aftermerge: false
