name: "Windows linters"

on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  windows-lint:
    runs-on: windows-2019 # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    steps:
      - name: Checkout datadog-agent repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #needed for 'git describe' to work

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.5"
          cache: "pip"
      - run: |
          python -m pip install -r requirements.txt
          If ($lastExitCode -ne "0") { throw "Previous command returned $lastExitCode" }

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version-file: ".go-version"

      - name: Install Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Set up runner
        run: |
          $ErrorActionPreference = 'Stop';
          # install dependencies
          inv -e install-tools
          If ($lastExitCode -ne "0") { throw "Previous command returned $lastExitCode" }
          inv -e deps
          If ($lastExitCode -ne "0") { throw "Previous command returned $lastExitCode" }

      # Run this first as it's quite quick compared to Go
      - name: Run Dotnet linter
        shell: bash # using bash so we don't have to check $lastExitCode all the time
        run: |
          dotnet format --verify-no-changes .\\tools\\windows\\DatadogAgentInstaller

      - name: Run Go linters
        shell: bash # using bash so we don't have to check $lastExitCode all the time
        run: |
          export PATH="/c/msys64/mingw64/bin:/c/msys64/usr/bin/:$PATH" # prepend msys, otherwise make from mingw gets used
          echo $PATH
          powershell.exe -Command ./tasks/winbuildscripts/pre-go-build.ps1
          inv -e rtloader.format --raise-if-changed
          inv -e linter.go --timeout 30
